# Generated by Django 6.0.3 on 2026-03-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, help_text='Ex: Ouvidoria, Infraestrutura, etc', max_length=100, verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('citizen', 'Cidadão'), ('analyst', 'Analista de Ouvidoria'), ('manager', 'Gestor'), ('admin', 'Administrador')], default='citizen', max_length=20, verbose_name='Tipo de usuário'),
        ),
    ]
